import WebUtils from "../WebUtils";

const innerTableData = [];

for (let i = 1; i < 4; ++i) {
    innerTableData.push({
    key: i+'',
    date: '2014-12-24 23:12:00',
    name: 'This is production name',
    upgradeNum: 'Upgraded: 56',
    item: i,
    item_desc:'Item name',
    quantity: 3*1,
    unit_price: 10,
    Subtotal: 100,
    tax: 2*i
    });
}

const _mockData = [
    {
    key: '1',
    name: 'Danish Raza',
    buyer: 'Danish Raza',
    value: 32,
    customer_id: "1100712",
    customer_name: "Danish Raza",
    po_id: "#4400000555",
    material: "material 1",
    order_ammount: 1881395.00,
    requirement:"Type I",
    due_date: "2022-10-09",
    valid_from: "2022-10-09",
    address: 'New York No. 1 Lake Park',
    status: 'Send',
    invoice_status:"Paid",
    invoice_no: "#123",
    title:"title 1",
    category: "category 1",
    inner_table: innerTableData,
    available_version: [
        {
            key: '1',
            name: 'Danish Raza',
            buyer: 'Danish Raza',
            value: 32,
            customer_id: "1100712",
            customer_name: "Danish Raza",
            po_id: "#4400000555",
            material: "material 1",
            order_ammount: 1881395.00,
            requirement:"Type I",
            due_date: "2022-10-09",
            valid_from: "2022-10-09",
            address: 'New York No. 1 Lake Park',
            status: 'Send',
            invoice_status:"Paid",
            invoice_no: "#123",
            title:"title 1",
            category: "category 1",
            certifying_body: "body 1",
            editor:"Editor 1",
            version:"Version 1",
            dol:"DOL 1",
            dop:"DOP 2",
            isbn:"ISBN 1",
            "ship_to":"Hyderabad",
            in_house_publication: "Publication 1",
            purchase_status:"Dispatched",
            po_status:"Received",
            type: "Type 1",
            settlement: "SM 1",    
            invoice_amount: 82112,
            revision: "R 01",
            inner_table: innerTableData,
        },
        {
                key: '1',
                name: 'Danish Raza',
                buyer: 'Danish Raza',
                value: 32,
                customer_id: "1100712",
                customer_name: "Danish Raza",
                po_id: "#4400000555",
                material: "material 1",
                order_ammount: 1881395.00,
                requirement:"Type I",
                due_date: "2022-10-09",
                valid_from: "2022-10-09",
                address: 'New York No. 1 Lake Park',
                status: 'Send',
                invoice_status:"Paid",
                invoice_no: "#123",
                title:"title 1",
                category: "category 1",
                certifying_body: "body 1",
                editor:"Editor 1",
                version:"Version 2",
                dol:"DOL 1",
                dop:"DOP 2",
                isbn:"ISBN 1",
                "ship_to":"Hyderabad",
                in_house_publication: "Publication 1",
                purchase_status:"Dispatched",
                po_status:"Received",
                type: "Type 1",
                settlement: "SM 1",    
                invoice_amount: 82112,
                revision: "R 01",
                inner_table: [innerTableData[0],innerTableData[1]],
        }
    ],
    certifying_body: "body 1",
    editor:"Editor 1",
    version:"Version 1",
    dol:"DOL 1",
    dop:"DOP 2",
    isbn:"ISBN 1",
    "ship_to":"Hyderabad",
    in_house_publication: "Publication 1",
    purchase_status:"Dispatched",
    po_status:"Approved",
    type: "Type 1",
    settlement: "SM 1",    
    invoice_amount: 82112,
    revision: "R 01",

    "transport_terms": '# 1',
    "ein": 'Decription 01',
    "gross_volume": 'M 1',
    "volume_unit": 100,
    "gross_weight": 100,
    "weight_unit": 100,
    "party_code": 'Version 01',
    "sealing_id": 'Version 01',
    size:100,
    quantity:100,
    "quantity_ship": 'Decription 02',
    "batch_id": 'T 2',
    "quantity_unit": 100,
    "ship_notice": 'No Notice'
    },
    {
    key: '2',
    name: 'Akshay Pai',
    buyer: 'Akshay Pai',
    invoice_status:"Overdue",
    value: 42,
    valid_from: "2022-10-10",
    order_ammount: 311520.00,
    requirement:"Type I",
    due_date: "2022-10-09",
    customer_id: "1700294",
    customer_name: "Akshay Pai",
    po_id: "#5500002705",
    material: "material 2",
    address: 'London No. 1 Lake Park',
    status: 'Payments',
    invoice_no: "#124",
    title:"title 2",
    category: "category 2",
    certifying_body: "body 2",
    editor:"Editor 2",
    version:"Version 2",
    dol:"DOL 2",
    dop:"DOP 2",
    isbn:"ISBN 2",
    in_house_publication: "Publication 2",
    purchase_status:"Received",
    "ship_to":"Agra",
    po_status:"Open Purchase Order",
    type: "Type 2",
    settlement: "SM 2",    
    invoice_amount: 62112,
    revision: "R 02",
    inner_table: innerTableData,
    "transport_terms": '# 2',
    "ein": 'Decription 02',
    "gross_volume": 'M 2',
    "volume_unit": 100,
    "gross_weight": 100,
    "weight_unit": 100,
    "party_code": 'Version 02',
    "sealing_id": 'Version 02',
    size:100,
    quantity:100,
    "quantity_ship": 'Decription 03',
    "batch_id": 'T 3',
    "quantity_unit": 100,
    "ship_notice": 'No Notice'
    }, 
    {
        inner_table: innerTableData,
        key: '4',
        name: 'Mukesh Kumar',
        buyer:"Mukesh Kumar",
        customer_id: "4300002632",
        customer_name: "Mukesh Kumar",
        invoice_Status:"Paid",
        po_id: "#4300002632",
        invoice_status:"Due",
        material: "material 4",
        valid_from: "2022-10-11",
        value: 32,
        order_ammount: 333000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        address: 'Sidney No. 1 Lake Park',
        status: 'Rejected',
        invoice_no: "#126",
        title:"title 4",
        category: "category 4",
        certifying_body: "body 4",
        editor:"Editor 4",
        version:"Version 4",
        dol:"DOL 4",
        dop:"DOP 4",
        isbn:"ISBN 4",
        "ship_to":"Lucknow",
        in_house_publication: "Publication 4",
        purchase_status:"Received",
        po_status:"Closed Purchase Order" ,
        type: "Type 3",
        settlement: "SM 3",    
        invoice_amount: 92112,
        revision: "R 03",
        "transport_terms": '# 3',
        "ein": 'Decription 03',
        "gross_volume": 'M 3',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 03',
        "sealing_id": 'Version 03',
        size:100,
        quantity:100,
        "quantity_ship": 'Decription 03',
        "batch_id": 'T 3',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '5',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Submitted",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Awaiting Buyer Approval",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '7',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Invoiced",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '8',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Received",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '10',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Accepted",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '1112',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Dispatched",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '112',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Partial Dispatch",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    },
    {
        key: '1212',
        inner_table: innerTableData,
        name: 'Danish Raza',
        buyer: 'Danish Raza',
        value: 32,
        customer_id: "1100712",
        customer_name: "Danish Raza",
        po_id: "#4500149543",
        material: "material 1",
        order_ammount: 235000.00,
        requirement:"Type I",
        due_date: "2022-10-09",
        valid_from: "2022-10-09",
        address: 'New York No. 1 Lake Park',
        status: 'Send',
        invoice_status:"Paid",
        invoice_no: "#123",
        title:"title 1",
        category: "category 1",
        certifying_body: "body 1",
        editor:"Editor 1",
        version:"Version 2",
        dol:"DOL 1",
        dop:"DOP 2",
        isbn:"ISBN 1",
        "ship_to":"Hyderabad",
        in_house_publication: "Publication 1",
        purchase_status:"Dispatched",
        po_status:"Advanced Delivery Notice Sent",
        type: "Type 4",
        settlement: "SM 4",    
        invoice_amount: 22112,
        revision: "R 04",
        "transport_terms": '# 4',
        "ein": 'Decription 04',
        "gross_volume": 'M 4',
        "volume_unit": 100,
        "gross_weight": 100,
        "weight_unit": 100,
        "party_code": 'Version 04',
        "sealing_id": 'Version 04',
        size:100,
        quantity:100,

        "quantity_ship": 'Decription 04',
        "batch_id": 'T 4',
        "quantity_unit": 100,
        "ship_notice": 'No Notice'
    }
];

export function changeTableParams(data) {
    return function (dispatch, getState) {
        if(data.init) {
            //Set loader true,
            dispatch({ type: 'CHANGE_LOADER_STATE', loading: true})
            //Make API call
          
            dispatch({ ...data, type: "SET_TABLE_DATA", data: _mockData})
        } else {
            dispatch({ ...data})
        }
    }
}

export function fetchTableDate(data) {
    return function (dispatch, getState) {
        //Set loader true
        dispatch({ type: 'CHANGE_LOADER_STATE', loading: true})

        //Make API call
        dispatch({ ...data, type: "SET_TABLE_DATA", data: _mockData})
    }
}