import { Table, Button } from 'antd';
import _ from "underscore";

const EwayTable = () => {
    const columns = [
        {
          title: 'Mode',
          dataIndex: 'Mode',
          width: 100,
        },
        {
          title: 'Vehicle Number',
          width: 100,
          dataIndex: 'Vehicle Number',
        //   sorter: (a, b) => a.age - b.age,
        },
        {
            title: 'Location (From)',
            dataIndex: 'Location (From)',
            width: 100,
        },
        {
            title: 'Location (To)',
            dataIndex: 'Location (To)',
            width: 100,
        },
        {
            title: 'Entered Date',
            dataIndex: 'Entered Date',
            width: 100,
        },
        {
            title: 'Entered By',
            dataIndex: 'Entered By',
            width: 100,
        }
    ];
    const data = [
        {
          key: '1',
          name: 'John Brown',
          age: 32,
          address: 'New York No. 1 Lake Park',
        },
        {
          key: '2',
          name: 'Jim Green',
          age: 42,
          address: 'London No. 1 Lake Park',
        }
    ];  
    const onChange = (pagination, filters, sorter, extra) => {
        console.log('params', pagination, filters, sorter, extra);
    };
    let metaData = {
        "e-Way Bill QR-Code Display": "",
        "e-Way Bill Number": "",
        "e-Way Bill Date": "",
        "Generated By": "",
        "Valid From": "",
        "Valid To": "",
        "GSTIN of Recipient": "",
        "Place of Delivery": "",
        "Invoice | Challan Number": "",
        "Invoice | Challan Date": "",
        "Value of Goods": "",
        "HSN Code": "",
        "Reason for Transportation": "",
        "Transport Number": "",
        "Transport Name": "",
        "Transport Document Name": "",
        "Transport Document Number": "",
        "Transport Document Date": "",
    }
    return (
        <div>
            <div className='matadata'>
                {
                    _.map(metaData, (value, key) => {
                        return <div className='matadata-row'><div className='text-bold'>{key}</div> : <div>{value}</div></div>
                    })
                }

            </div>
            <Table columns={columns} dataSource={data} onChange={onChange} pagination={false}/>

            <div className='button-wrapper'>
                <Button type="primary" >Print</Button>
                <Button key="submit" type="primary" >Detailed Document Print</Button>
                <Button type="primary">Save PDF</Button>
            </div>
        </div>
    )
  } 
  
  export default EwayTable;